services:
  favsongs:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    image: favsongs-web:latest
    environment:
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      SPOTIFY_HTTP_TIMEOUT_SECONDS: ${SPOTIFY_HTTP_TIMEOUT_SECONDS:-20}
      TOKEN_SKEW_SECONDS: ${TOKEN_SKEW_SECONDS:-60}
      MAX_LOOKUP_CANDIDATES: ${MAX_LOOKUP_CANDIDATES:-12}
      MAX_PUBLIC_PLAYLISTS: ${MAX_PUBLIC_PLAYLISTS:-200}
      MAX_LIKED_PLAYLISTS: ${MAX_LIKED_PLAYLISTS:-4}
      MAX_TRACKS_PER_LIKED_PLAYLIST: ${MAX_TRACKS_PER_LIKED_PLAYLIST:-75}
      DEFAULT_PLAYLIST_TRACK_LIMIT: ${DEFAULT_PLAYLIST_TRACK_LIMIT:-100}
      LIKED_PLAYLIST_KEYWORDS: ${LIKED_PLAYLIST_KEYWORDS:-liked,favorite,favourites,favorites,saved,heart,hearts}
    expose:
      - "8000"
    restart: unless-stopped
    init: true
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/healthz', timeout=5).read()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    depends_on:
      - favsongs
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
