services:
  favsongs-local:
    build:
      context: .
      dockerfile: Dockerfile
    image: favsongs-web:local
    env_file:
      - .env.local
    environment:
      FAVSONGS_DATA_DIR: /app/data
      FAVSONGS_DB_PATH: /app/data/favsongs-local.db
      DEFAULT_PLAYLIST_NAME: ${DEFAULT_PLAYLIST_NAME:-Favourite Songs - Whatsit}
      PLAYLIST_NAME_SUFFIX: ${PLAYLIST_NAME_SUFFIX:-[LOCAL]}
      LOCAL_ONLY_MODE: ${LOCAL_ONLY_MODE:-true}
      ALLOWED_NETWORKS: ${ALLOWED_NETWORKS:-127.0.0.0/8,::1/128,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,169.254.0.0/16,fe80::/10,fc00::/7}
      TRUST_FORWARDED_FOR: ${TRUST_FORWARDED_FOR:-false}
      MAX_CONNECTED_USERS: ${MAX_CONNECTED_USERS:-6}
    ports:
      - ${APP_PORT:-8000}:8000
    volumes:
      - favsongs_local_data:/app/data
    restart: unless-stopped
    init: true
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/healthz', timeout=5).read()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  favsongs_local_data:
